/* automatically generated by rust-bindgen */

#![allow(bad_style, dead_code)]

extern "C" {
    #[link_name = "\u{1}_alloc_and_set"]
    pub fn alloc_and_set(size: ::std::os::raw::c_uint);
}
extern "C" {
    #[link_name = "\u{1}_free_alloc"]
    pub fn free_alloc();
}
extern "C" {
    #[link_name = "\u{1}_set_buffer"]
    pub fn set_buffer(b: *mut f32);
}
extern "C" {
    #[link_name = "\u{1}_write_f32"]
    pub fn write_f32(offset: ::std::os::raw::c_int, v: f32);
}
